learning_logs/urls.py
""" Определяет схемы URL для learning_logs """
from django.urls import path

from . import views

app_name = 'learning_logs'
urlpatterns = [
    path('', views.index, name='index'),
    path('topics/', views.topics, name='topics'),
    
    #Страница с подробной информацией по отдельной теме
    path('topics/<int:topic_id>/', views.topic, name='topic'),

    #Страница для добавления новой темы
    path('new_topic/', views.new_topic, name='new_topic'),

    #Страница для добавления новой записи
    path('new_entry/<int:topic_id>/', views.new_entry, name='new_entry'),
] 

ll_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('learning_logs.urls')),
]

learning_logs/models.py
from django.db import models

class Topic(models.Model):
    """ Тема которую изучает пользователь """
    text = models.CharField(max_length=150)
    data_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        """ Возвращает строковое представление модели """
        return self.text
    
class Entry(models.Model):
    """  Статья на определённую тему """
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural="entries"

    def __str__(self):
        """ Возвращает строковое представление модели """
        return f"{self.text[:50]}..."

learning_logs/forms.py
from django import forms

from .models import Topic, Entry

class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text']
        labels = {'text': ''}

class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text':''}
        widgets = {'text': forms.Textarea(attrs={'cols':80})}

learning_logs/views.py
from django.shortcuts import render, redirect

from .models import Topic
from .forms import TopicForm, EntryForm

def index(request):
    """ Главная страница приложения """
    return render(request, 'learning_logs/index.html')

def topics(request):
    """ Выводит список тем """
    topics = Topic.objects.order_by('data_added')
    context = {'topics': topics}
    return render(request, 'learning_logs/topics.html', context)

def topic(request, topic_id):
    """ Выводит одну тему и все её записи. """
    topic = Topic.objects.get(id=topic_id)
    entries = topic.entry_set.order_by('-date_added')
    context = {'topic': topic, 'entries': entries}
    return render(request, 'learning_logs/topic.html', context)

def new_topic(request):
    """ Добовляет новую тему """
    if request.method != 'POST':
        # Данные не отправились, а создаётся пустая форма
        form = TopicForm()
    else:
        #Отправленны данные POST, ещё проверить введённые данные
        form = TopicForm(data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('learning_logs:topics')

    #Вывести пустую или не действительную форму
    context = {'form': form}
    return render(request, 'learning_logs/new_topic.html', context) 

def new_entry(request, topic_id):
    """Добавляет запись по конкретной теме"""
    topic = Topic.objects.get(id=topic_id)

    if request.method != 'POST':
        # Данные не отправились, создаётся пустая форма
        form = EntryForm()
    else:
        # Отправленные данные POST, обработать данные
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()
            return redirect('learning_logs:topic', topic_id=topic_id)

        #Вывести пустую или недействительную форму
    context = {'topic': topic, 'form': form}
    return render(request, 'learning_logs/new_entry.html', context) 

learning_logs/templates/learning_logs/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <p>
        <a href="{% url 'learning_logs:index' %}">Журнал статей</a>  -  
        <a href="{% url 'learning_logs:topics' %}">Темы</a>
    </p>
    {% block content %}{% endblock content %}
</body>
</html>

learning_logs/templates/learning_logs/index.html
{% extends "learning_logs/base.html" %}

{% block content %}
<p>Здесь будут записаны статьи по обучающим материалам</p>
{% endblock content %}

learning_logs/templates/learning_logs/new_entry.html
{% extends "learning_logs/base.html" %}

{% block content %}

<p><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></p>

<p>Запись новой статьи</p>
<form action="{% url 'learning_logs:new_entry' topic.id %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit">Запись статьи</button>
</form>

{% endblock content %}

learning_logs/templates/learning_logs/new_topic.html
{% extends "learning_logs/base.html" %}

{% block content %}
    <p>Запись темы:</p>
    <form action="{% url 'learning_logs:new_topic' %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button name="submit">Записать</button>
    </form>
{% endblock content %}

learning_logs/templates/learning_logs/topic.html
{% extends 'learning_logs/base.html' %}

{% block content %}
    <p>Тема: {{ topic }}</p>
    <p>Текст статьи:</p>
    
        
    <ul>
        {% for entry in entries %}
            <li>
               <p>{{ entry.data_added|date:'M d, Y H:i' }}</p>
               <p>{{ entry.text|linebreaks }}</p> 
            </li>
        {% empty %}
            <li>
                Добавте записи
            </li>
        {% endfor %}
    </ul>
    
    <p>
        <a href="{% url 'learning_logs:new_entry' topic.id %}">Запись новой статьи</a>
    </p>


{% endblock content %}

learning_logs/templates/learning_logs/topics.html
{% extends "learning_logs/base.html" %}

{% block content %}
<p>ТЕМЫ</p>
<ul>
    {% for topic in topics %}
        <li>{{ topic }}</li>
    {% empty %}
        <li>Нет тем для выбора</li>
    {% endfor %}
</ul>
<a href="{% url 'learning_logs:new_topic' %}">Добавить тему</a>
{% endblock content %}